alias ll='ls -alFh'
alias config='/usr/bin/git --git-dir=/home/will/.cfg/ --work-tree=/home/will'
alias grep='grep --color=auto'
alias du='du -h'
alias fvim='vim $(fzf)'
alias fvi='fvim'
alias dirs='dirs -v'
alias clauded='claude --dangerously-skip-permissions'

alias home='cd /mnt/c/Users/wgb.PI/'
alias proj='cd /mnt/c/projects/'
alias exp='explorer.exe .'
alias psh='powershell.exe'
alias powershell='powershell.exe'
alias cmd='cmd.exe'
alias wchrome="/mnt/c/Program Files/Google/Chrome/Application/chrome.exe"
